// Code generated by protoc-gen-go.
// source: wire.proto
// DO NOT EDIT!

/*
Package wirepb is a generated protocol buffer package.

It is generated from these files:
	wire.proto

It has these top-level messages:
	RequestHeader
	ResponseHeader
*/
package wirepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RequestHeader struct {
	Method string `protobuf:"bytes,1,opt,name=Method" json:"Method,omitempty"`
	Seq    uint64 `protobuf:"varint,2,opt,name=Seq" json:"Seq,omitempty"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}

type ResponseHeader struct {
	Method string `protobuf:"bytes,1,opt,name=Method" json:"Method,omitempty"`
	Seq    uint64 `protobuf:"varint,2,opt,name=Seq" json:"Seq,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
